s2_infer:
  max_inference_time: 0.0026 # seconds, based on the observed inference time of the current S2 model on 5090 GPU
  min_inference_time: 0.6316 # seconds, based on the observed inference time of the current S2 model on 5090 GPU

# On-device inference latency
s1_infer:
  nextdit:
    # alpha: 0.093283 # N
    # beta: 0.000794 # N*B
    # c: 0.240866
    alpha: 0.082530 # N
    beta: 0.000875 # N*B
    c: 0.228075
  navdp:
    alpha: 0.041678 # N
    beta: 0.000540 # N*B
    c: 0.333653